### ISSUE TITLE
More than two waypoints cause error!

### ISSUE THREAD

**Issue by otodockal** [perliedman/lrm-mapbox#4]
Hi,
I experience this error about two days now when I add more than two waypoints.
Maybe something changed on Mapbox side, but I'm not in yet...

**TypeError: Cannot read property 'lat' of undefined**

Check out this row:
https://github.com/perliedman/lrm-mapbox/blob/master/src/L.Routing.Mapbox.js#L220

...looks like when you create more than two waypoints, size of array wpIndices is always smaller. It accesses index here:
https://github.com/perliedman/leaflet-routing-machine/blob/983201565c7417128c85b6a26b83653902f6cbfe/src/L.Routing.Line.js#L88

I did quick fix in my custom L.Routing.Mapbox.js script like this, but it's not correct, of course...
`
if (wpIndices.length < waypoints.length) wpIndices.push(coordinates.length - 1);
`

Thank you.

**Comment by petervojtek** [comment]
hi, I face this issue as well, it began maybe 2 days ago.

**Comment by perliedman** [comment]
This appears to be a regression in Mapbox Directions.

I've debugged it, and when you add a third waypoint, the route returned from the API no longer contains the last coordinate of the route - that means, the actual coordinate of the last waypoint is not part of the route if it has more than two waypoints.

Anyway, this is fixed with a workaround in the code, I will make a 1.0.4 release shortly that will contain the fix.

**Comment by petervojtek** [comment]
@perliedman, thank you a lot for quick response and new release :)
